version: "3.8"
services:
  site:
    read_only: true
    command: ["bundle", "exec", "jekyll", "serve"]
    image: jekyll/jekyll:stable
    tmpfs:
      - /tmp
    volumes:
      - .:/srv/jekyll
      - ./vendor/home/jekyll:/home/jekyll
      - ./vendor/usr/gem:/usr/gem
      - ./vendor/var/jekyll:/var/jekyll
      - ./vendor/bundle:/usr/local/bundle
      - ./vendor/npm:/root/.npm
      - ./vendor/node/config:/root/.config
    ports:
      - "4000:4000"
      - "35729:35729"
