#!/usr/bin/env bash
set -e # halt script on error

mkdir _site
chmod a+w Gemfile.lock _site

# Install dependencies
docker-compose run site bundle install

# Hack - see https://github.com/jekyll/jekyll/issues/5423
docker-compose run site gem uninstall -x -I ffi
docker-compose run site gem install ffi --platform=ruby

# Build and test _site
docker-compose run site rake test

docker run -v $(pwd)/_site:/app stratdat/html5validator

#node --version
#./node_modules/a11y/cli.js --help
#./node_modules/a11y/cli.js {_site/*.html,_site/**/*.html}
