#!/usr/bin/env bash
set -e # halt script on error

# bundle install

bundle exec jekyll build
bundle exec htmlproofer ./_site --disable-external
$HOME/.local/bin/html5validator --root ./_deploy

#node --version
#./node_modules/a11y/cli.js --help
#./node_modules/a11y/cli.js {_site/*.html,_site/**/*.html}
