#!/usr/bin/env bash

set -e # halt script on error

key=$encrypted_df59e13927ec_key
iv=$encrypted_df59e13927ec_iv

openssl aes-256-cbc \
  -K $key \
  -iv $iv \
  -in .travis/deploy-key.enc \
  -out .travis/deploy-key -d

eval "$(ssh-agent -s)" #start the ssh agent
chmod 600 .travis/deploy-key
ssh-add .travis/deploy-key

#git diff --quiet --exit-code --cached || git commit -m 'Add build artefacts'
set +e

# git diff-tree -r --name-only --no-commit-id master | grep '^_site/' &> /dev/null

ls -l _site

grep -- '-- change' _site/index.html

git diff-tree -r --name-only --no-commit-id master

git diff-tree -r --name-only --no-commit-id master | grep '^_site/'

git status -s | grep "^..\s_site"

git status -s | grep -q "^..\s_site"

status=$?

echo status=$status

set -e
if [ $status == 0 ]; then
  git add -A
  git commit -m 'Add build artefacts'
  git remote add pages git@github.com:mds-validator/validator.com.au.git
  git push pages `git subtree split --prefix _site 2> /dev/null`:gh-pages --force
fi
