#!/usr/bin/env bash

set -e # halt script on error

key=$encrypted_df59e13927ec_key
iv=$encrypted_df59e13927ec_iv

openssl aes-256-cbc \
  -K $key \
  -iv $iv \
  -in .travis/deploy-key.enc \
  -out .travis/deploy-key -d

eval "$(ssh-agent -s)" #start the ssh agent
chmod 600 .travis/deploy-key
ssh-add .travis/deploy-key

perl -n -i -e "print unless /^_site\/$/" ./.gitignore 
git add .
git commit -m "Edit .gitignore to publish"
git remote add pages git@github.com:mds-validator/validator.com.au.git
git push pages `git subtree split --prefix _site 2> /dev/null`:gh-pages --force
git reset HEAD~
git checkout .gitignore
